### ISSUE TITLE
Tests don't complete

### ISSUE THREAD

**Issue by phuddha** [IRL2/nanover-protocol#271]
After the last test pass message on Mac the tests just hang. 

This was the last message

=========================================== 870 passed, 6 warnings in 313.77s (0:05:13) ===========================================

Looks like pytest never completes or is deadlocked. This is consistent on Mac (happens every time). Ctrl C interrupt provides:

^CException ignored in: <module 'threading' from '/opt/anaconda3/envs/nanover-dev/lib/python3.12/threading.py'>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/nanover-dev/lib/python3.12/threading.py", line 1572, in _shutdown
    atexit_call()
  File "/opt/anaconda3/envs/nanover-dev/lib/python3.12/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/opt/anaconda3/envs/nanover-dev/lib/python3.12/threading.py", line 1126, in join
    self._wait_for_tstate_lock()
  File "/opt/anaconda3/envs/nanover-dev/lib/python3.12/threading.py", line 1146, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:

**Comment by Ragzouken** [comment]
openmm runner test seems to be an issue

**Comment by Ragzouken** [comment]
openmm runner constructor throws exception so server is never shutdown
