### ISSUE TITLE
Poll on closed channel in tests

### ISSUE THREAD

**Issue by jbarnoud** [IRL2/nanover-protocol#66]
A test issues this warning systematically. This behaviour needs to be checked, even though it has been present for years.

```
python-libraries/nanover-core/tests/utilities/test_grpc_utilities.py::test_subscribe_unused_channel_closed
  /home/jon/.mambaforge/envs/nanover/lib/python3.10/site-packages/_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-1060 (_run)
  
  Traceback (most recent call last):
    File "/home/jon/.mambaforge/envs/nanover/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
      self.run()
    File "/home/jon/.mambaforge/envs/nanover/lib/python3.10/threading.py", line 953, in run
      self._target(*self._args, **self._kwargs)
    File "src/python/grpcio/grpc/_cython/_cygrpc/thread.pyx.pxi", line 53, in grpc._cython.cygrpc._run_with_context._run
    File "/home/jon/.mambaforge/envs/nanover/lib/python3.10/site-packages/grpc/_channel.py", line 1828, in _poll_connectivity
      connectivity = channel.check_connectivity_state(try_to_connect)
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 529, in grpc._cython.cygrpc.Channel.check_connectivity_state
    File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 534, in grpc._cython.cygrpc.Channel.check_connectivity_state
  ValueError: Cannot invoke RPC: Channel closed!
```

**Comment by Ragzouken** [comment]
Test docstring:
```
Test that subscribing a closed channel's connectivity does not call the
callback. This will cause an exception on another thread, but it can't be
tested for.
```

Is there any way to suppress this do you think?

**Comment by jbarnoud** [comment]
Purest has a way to capture warnings for a specific test. https://docs.pytest.org/en/7.1.x/how-to/capture-warnings.html
