### ISSUE TITLE
What happens when the server receives a misformed request to update the locks?

### ISSUE THREAD

**Issue by jbarnoud** [IRL2/nanover-protocol#82]
A request to update the locks contains a ``Struct`` with the state keys to update as keys, and either a duration in seconds or `None` as values. Both the python and the rust servers check for misformatted a ``Struct`` (see bellow for where it is checked) but what happens in practice if there is an error? Is that behaviour the one we want? In any case, it should be documented.

In python: https://github.com/IRL2/nanover-protocol/blob/6b7f45bed2c325c85120b2a5157bc9101e493052/python-libraries/nanover-core/src/nanover/state/state_service.py#L220-L221

In rust: https://github.com/IRL2/nanover-rs/blob/cf86bf1da2ec037dc73b7ec96d169c60ec839ca0/nanover-rs/src/services/state.rs#L157-L159

**Comment by Ragzouken** [comment]
In practice:

```
>>> client.attempt_update_multiplayer_locks({ "somekey": "non-number" })
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mark\anaconda3\envs\nanover\lib\site-packages\nanover\app\client.py", line 61, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\mark\anaconda3\envs\nanover\lib\site-packages\nanover\app\client.py", line 651, in attempt_update_multiplayer_locks
    return self._multiplayer_client.attempt_update_locks(update)  # type: ignore
  File "C:\Users\mark\anaconda3\envs\nanover\lib\site-packages\nanover\core\nanover_client.py", line 166, in attempt_update_locks
    response = self._state_stub.UpdateLocks(request)
  File "C:\Users\mark\anaconda3\envs\nanover\lib\site-packages\grpc\_channel.py", line 1176, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Users\mark\anaconda3\envs\nanover\lib\site-packages\grpc\_channel.py", line 1005, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception calling application: Lock duration must be a real number."
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: Lock duration must be a real number.", grpc_status:2, created_time:"2024-05-06T12:38:24.0199653+00:00"}"
```

**Comment by jbarnoud** [comment]
This is the behaviour that is documented in <https://irl2.github.io/nanover/concepts/base-protocol.html#state-locks>, then. I may add a note about the request failing.

Thank you.

(I keep the issue open to remember to add said note.)
